FROM golang:1.23-alpine

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify && go mod tidy

COPY . .
RUN go install github.com/go-delve/delve/cmd/dlv@latest