FROM golang:1.23 AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build -o main ./cmd/jubawink

FROM gcr.io/distroless/static:nonroot

WORKDIR /

COPY --from=builder /app/main /

EXPOSE 8080

USER nonroot:nonroot

CMD ["/main"]
