# Define services
services:
  # App Service
  gin-server:
    # Configuration for building the docker image for the service
    container_name: gin-server
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    command: ["go","run","cmd/jubawink/main.go"]
    depends_on:
      - database
      - redis
    ports:
      - "4000:8080"
    env_file:
      - .env
    volumes:
      - ./api:/usr/src/app/api
      - ./cmd:/usr/src/app/cmd
      - ./internal:/usr/src/app/internal
      - ./pkg:/usr/src/app/pkg
      - ./docs:/usr/src/app/docs
  database:
    container_name: postgres-database
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - database.env
    ports:
      - 5432:5432
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./internal/redis/redis-stack.conf:/redis-stack.conf